### ISSUE TITLE
PowerShell Workflow returns "Error: 'Cannot find the type for custom attribute 'Parameter '. Make sure that the assembly that contains this type is loaded.'"

### ISSUE THREAD

**Issue by egbill3eagle** [Microsoft/MIMWAL#26]
I have a PowerShell workflow that is failing to run even with the simplest of PowerShell scripts. Every run returns:
> Error Invoking PowerShell script. Error: 'Cannot find the type for custom attribute 'Parameter '. Make sure that the assembly that contains this type is loaded.'

The named parameter being provided is `"input"` with the expression `[//Target/DisplayName]`
The script being run is: 
```
Param(
    [Parameter (Mandatory=$true)]$input
)

"Test File" | Out-File c:\temp\testfile.txt
$input | Out-File c:\temp\testfile.txt
```

**Comment by NileshGhodekar** [comment]
What is the detailed error in the WAL event log? In all likely hood, the script pasted in not exactly what is configured in the WF.

**Comment by egbill3eagle** [comment]
There are 2 errors in WAL.

**Error 1: Event ID 40403**
`WAL (2.16.1028.0): 01/19/2017 07:43:32.1159: RunPowerShellScript : RunScript: Exception in 'RunPowerShellScript : RunScript'. Details: MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Exceptions.WorkflowActivityLibraryException: Error Invoking PowerShell script. Error: 'Cannot find the type for custom attribute 'Parameter '. Make sure that the assembly that contains this type is loaded.' ---> System.Management.Automation.RuntimeException: Cannot find the type for custom attribute 'Parameter '. Make sure that the assembly that contains this type is loaded.
   at System.Management.Automation.AttributeNode.GetCustomAttributeObject()
   at System.Management.Automation.AttributeNode.GetCustomAttribute()
   at System.Management.Automation.ParameterNode.HasParameterAttribute()
   at System.Management.Automation.ParameterDeclarationNode.InitializeRuntimeDefinedParameters(Boolean& useCmdletBinding)
   at System.Management.Automation.ScriptBlock.InitializeAttributesAndParameters()
   at System.Management.Automation.ScriptBlock.get_CmdletBindingAttribute()
   at System.Management.Automation.CommandMetadata..ctor(ScriptBlock scriptblock, String commandName, ExecutionContext context)
   at System.Management.Automation.ScriptBlock.get_ParameterMetadata()
   at System.Management.Automation.ScriptParameterBinderController..ctor(ScriptBlock script, InvocationInfo invocationInfo, ExecutionContext context, InternalCommand command, Boolean useLocalScope)
   at System.Management.Automation.ScriptCommandProcessor.NewParameterBinderController(InternalCommand command)
   at System.Management.Automation.CommandProcessorBase.get_ParameterBinderController()
   at System.Management.Automation.ScriptCommandProcessor.Prepare(CommandParameterInternal[] parameters)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(CommandParameterInternal[] parameters)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
   --- End of inner exception stack trace ---.
Extended Properties:
WorkflowInstanceId: 8d75e2d4-e7da-47ae-a15c-b1de70086e8d
TargetId: b7c2b352-9633-4763-a526-67d51c48a400
RequestId: a6b64b74-b527-4987-b36e-4964e11b6058
WorkflowDefinitionId: 49b9dfa2-c9b1-4481-bfef-36f789330775
ActorId: 7fb2b853-24f0-4498-9534-4e10589723c4`

**Error 2: Event ID 40403**
`WAL (2.16.1028.0): 01/19/2017 07:43:32.1159: RunPowerShellScript : RunScript: Exception in 'RunPowerShellScript : RunScript'. Details: MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Exceptions.WorkflowActivityLibraryException: Error Invoking PowerShell script. Error: 'Cannot find the type for custom attribute 'Parameter '. Make sure that the assembly that contains this type is loaded.' ---> System.Management.Automation.RuntimeException: Cannot find the type for custom attribute 'Parameter '. Make sure that the assembly that contains this type is loaded.
   at System.Management.Automation.AttributeNode.GetCustomAttributeObject()
   at System.Management.Automation.AttributeNode.GetCustomAttribute()
   at System.Management.Automation.ParameterNode.HasParameterAttribute()
   at System.Management.Automation.ParameterDeclarationNode.InitializeRuntimeDefinedParameters(Boolean& useCmdletBinding)
   at System.Management.Automation.ScriptBlock.InitializeAttributesAndParameters()
   at System.Management.Automation.ScriptBlock.get_CmdletBindingAttribute()
   at System.Management.Automation.CommandMetadata..ctor(ScriptBlock scriptblock, String commandName, ExecutionContext context)
   at System.Management.Automation.ScriptBlock.get_ParameterMetadata()
   at System.Management.Automation.ScriptParameterBinderController..ctor(ScriptBlock script, InvocationInfo invocationInfo, ExecutionContext context, InternalCommand command, Boolean useLocalScope)
   at System.Management.Automation.ScriptCommandProcessor.NewParameterBinderController(InternalCommand command)
   at System.Management.Automation.CommandProcessorBase.get_ParameterBinderController()
   at System.Management.Automation.ScriptCommandProcessor.Prepare(CommandParameterInternal[] parameters)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(CommandParameterInternal[] parameters)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
   --- End of inner exception stack trace ---.
Extended Properties:
WorkflowInstanceId: 8d75e2d4-e7da-47ae-a15c-b1de70086e8d
TargetId: b7c2b352-9633-4763-a526-67d51c48a400
RequestId: a6b64b74-b527-4987-b36e-4964e11b6058
WorkflowDefinitionId: 49b9dfa2-c9b1-4481-bfef-36f789330775
ActorId: 7fb2b853-24f0-4498-9534-4e10589723c4`

**Comment by NileshGhodekar** [comment]
so 'Parameter '. Strange, but looks like the unnecessary spacing is causing the issue in System.Management.Automation.

**Comment by NileshGhodekar** [comment]
Closing the issue as seems resolved.
